const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const {pathToFileURL} = require('node:url');
const path = require('node:path');
require('node:fs').mkdirSync('tmp', {recursive:true});
const url = pathToFileURL(path.resolve('snake.html')).href;
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(url);
  assert.equal(await page.locator('#state-label').innerText(), '等待开始');
  await page.locator('#theme').click();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
  await page.locator('#theme').click();
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  await page.locator('#manual').click();
  assert.equal(await page.evaluate(() => document.activeElement.id), 'board');
  await page.keyboard.press('ArrowDown');
  await page.waitForTimeout(600);
  await page.locator('#pause').click();
  const pausedSteps = await page.locator('#steps').innerText();
  await page.waitForTimeout(350);
  assert.equal(await page.locator('#steps').innerText(), pausedSteps);
  assert.equal(await page.locator('#state-label').innerText(), '已暂停');
  await page.locator('#pause').click();
  await page.waitForTimeout(600);
  assert.notEqual(await page.locator('#steps').innerText(), pausedSteps);
  await page.keyboard.press('Space');
  assert.equal(await page.locator('#state-label').innerText(), '已暂停');
  const spaceSteps = await page.locator('#steps').innerText();
  await page.waitForTimeout(200);
  assert.equal(await page.locator('#steps').innerText(), spaceSteps);
  await page.keyboard.press('Space');
  assert.equal(await page.locator('#state-label').innerText(), '进行中');
  await page.locator('#speed').selectOption('45');
  await page.locator('#auto').click();
  // This run uses the real animation timer, normal Math.random and no further gameplay input.
  await page.waitForFunction(() => Number(document.getElementById('eaten').textContent) >= 15, null, {timeout:30000});
  assert.equal(await page.locator('#state-label').innerText(), '进行中');
  assert.match(await page.locator('#challenge-label').innerText(), /达标/);
  console.log('AI browser run:', await page.locator('#steps').innerText(), 'foods:', await page.locator('#eaten').innerText());
  await page.locator('#route').check();
  await page.screenshot({path:'tmp/snake-desktop.png',fullPage:true});
  await page.locator('#pause').click();
  for (const width of [390, 320]) {
    await page.setViewportSize({width,height:844});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.evaluate(() => scrollTo(0,0));
    await page.screenshot({path:`tmp/snake-mobile-${width}.png`,fullPage:true});
  }
  await page.locator('#theme').click();
  await page.setViewportSize({width:1440,height:1100});
  await page.locator('#pause').click();
  await page.screenshot({path:'tmp/snake-light.png',fullPage:true});
  await page.locator('#pause').click();
  await page.setViewportSize({width:390,height:844});
  await page.locator('#manual').click();
  assert((await page.locator('.game-panel').boundingBox()).y < 2);
  await page.getByRole('button', {name:'向下',exact:true}).click();
  await page.waitForTimeout(170);
  await page.locator('#pause').click();
  assert.equal(await page.locator('#state-label').innerText(), '已暂停');
  await page.reload();
  const box = await page.locator('canvas').boundingBox();
  await page.mouse.move(box.x+box.width/2, box.y+box.height/2);
  await page.mouse.down();
  await page.mouse.move(box.x+box.width/2, box.y+box.height/2+40);
  await page.mouse.up();
  assert.equal(await page.locator('#state-label').innerText(), '进行中');
  await page.locator('#pause').click();
  await page.goto(pathToFileURL(path.resolve('index.html')).href);
  await page.getByRole('link', {name:'开始玩贪吃蛇'}).click();
  assert(page.url().endsWith('/snake.html'));
  assert.deepEqual(errors, []);
  console.log('PASS: file:// standalone, light/dark persistence, arrows, pause/resume, real-time AI >=15, mobile widths, no script errors');
  await browser.close();
})().catch(e => {console.error(e);process.exit(1);});
