const {chromium} = require('playwright');
const {pathToFileURL} = require('node:url');
const path = require('node:path');
require('node:fs').mkdirSync('tmp', {recursive:true});
const assert = require('node:assert/strict');
const url = pathToFileURL(path.resolve('snake.html')).href;
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const page = await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(url); await page.evaluate(() => localStorage.clear()); await page.reload();
  assert.equal(await page.locator('#history-count').innerText(), '0 / 10');
  await page.locator('#manual').click();
  await page.locator('#auto').click();
  assert.equal(await page.locator('#history-count').innerText(), '1 / 10');
  assert.match(await page.locator('#history-list li').first().innerText(), /手动 · 重新开局/);
  for (let i = 0; i < 11; i++) await page.locator(i % 2 ? '#auto' : '#manual').click();
  assert.equal(await page.locator('#history-count').innerText(), '10 / 10');
  assert.equal(await page.locator('#history-list li').count(), 10);
  assert.equal(await page.locator('#history-list li:visible').count(), 3);
  await page.locator('#history-toggle').click();
  assert.equal(await page.locator('#history-list li:visible').count(), 10);
  await page.reload();
  assert.equal(await page.locator('#history-count').innerText(), '10 / 10');
  assert.equal(await page.locator('#history-list li:visible').count(), 3);
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#history-clear').click();
  assert.equal(await page.locator('#history-count').innerText(), '0 / 10');
  await page.locator('#manual').click();
  await page.waitForFunction(() => document.getElementById('state-label').textContent === '本局结束', null, {timeout:5000});
  assert.equal(await page.locator('#history-count').innerText(), '1 / 10');
  assert.match(await page.locator('#history-list li').first().innerText(), /手动 · 撞到墙壁了/);
  assert.deepEqual(errors, []);
  console.log('PASS: new-game append, terminal append, 10-item cap, collapsed/full list, persistence, clear, mobile, no page errors');
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
