"""Reproduce the real AI-generated save() error without requiring an Ngspice DLL."""
import inspect
from importlib.metadata import version
from PySpice.Spice.Netlist import Circuit
from PySpice.Spice.Simulation import CircuitSimulation

print('PySpice version:', version('PySpice'))
sim = CircuitSimulation(Circuit('Save API reproduction'))
sim.SIMULATOR = 'ngspice'  # Serialize a deck without loading the native simulator.
try:
    # Original incorrect line generated by Codex during the MOS experiment.
    sim.save('all', '@m1[gm]', '@m1[gds]', '@m1[id]')
except TypeError as error:
    print('Original call failed:', error)
else:
    raise AssertionError('Error was not reproduced; check the PySpice version.')
print('Implementation evidence:')
print('\n'.join(line.strip() for line in inspect.getsource(CircuitSimulation.save).splitlines()
                if 'set(*args)' in line))
sim.save(['v(gate)', 'v(drain)', '@m1[gm]', '@m1[gds]', '@m1[id]'])
assert 'v(gate)' in str(sim) and '@m1[gm]' in str(sim)
print('PASS: one list argument works; explicit vectors survive serialization.')
